"use client";

import { useEffect, useRef, useState } from "react";
import { archiveLender, deleteLender, saveLender } from "@/app/admin/actions";

type Lender = Record<string, unknown> & { _id: string; name: string; slug: string; lenderType: string; displayOrder: number; published: boolean; archivedAt?: string | null; comparison?: Record<string, string> };
const comparisonFields = [["securedLoan", "Secured loan", "secured"], ["unsecuredLoan", "Unsecured loan", "unsecured"], ["securedRate", "Secured rate", "securedRate"], ["unsecuredRate", "Unsecured rate", "unsecuredRate"], ["moratorium", "Moratorium", "moratorium"], ["tenure", "Tenure", "tenure"], ["foreclosure", "Foreclosure charges", "foreclosure"], ["processingFee", "Processing fee", "fee"]] as const;

export function LenderManager({ lenders }: { lenders: Lender[] }) {
  const [editor, setEditor] = useState<Lender | null | undefined>(undefined);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (editor !== undefined) dialog.current?.showModal(); }, [editor]);
  const close = () => { dialog.current?.close(); setEditor(undefined); };
  return <>
    <div className="cw-admin-panel-head"><div><h2>Lenders</h2><p className="cw-admin-kicker">Published records are immediately available to the public lender display.</p></div><button className="cw-admin-primary" onClick={() => setEditor(null)}>Add lender</button></div>
    <section className="cw-admin-panel"><div className="cw-admin-table-wrap"><table><thead><tr><th>Lender</th><th>Category</th><th>Visibility</th><th>Order</th><th>Actions</th></tr></thead><tbody>{lenders.map((lender) => <tr key={lender._id}><td><strong>{lender.name}</strong>{lender.archivedAt && <small className="cw-admin-muted">Archived</small>}</td><td>{lender.lenderType}</td><td><span className={`cw-admin-badge ${lender.published && !lender.archivedAt ? "" : "cw-status-closed"}`}>{lender.published && !lender.archivedAt ? "Published" : "Hidden"}</span></td><td>{lender.displayOrder}</td><td><div className="cw-admin-actions"><button type="button" onClick={() => setEditor(lender)}>Edit</button>{!lender.archivedAt && <form action={archiveLender}><input type="hidden" name="id" value={lender._id}/><button className="secondary">Archive</button></form>}<form action={deleteLender} onSubmit={(event) => { if (!confirm(`Permanently delete ${lender.name}? This cannot be undone.`)) event.preventDefault(); }}><input type="hidden" name="id" value={lender._id}/><input type="hidden" name="confirm" value="DELETE"/><button className="cw-admin-danger">Delete</button></form></div></td></tr>)}</tbody></table></div></section>
    <dialog ref={dialog} className="cw-admin-dialog" onCancel={close} aria-labelledby="lender-editor-title"><LenderEditor lender={editor ?? undefined} close={close}/></dialog>
  </>;
}

function LenderEditor({ lender, close }: { lender?: Lender; close: () => void }) {
  const form = useRef<HTMLFormElement>(null); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const dirty = useRef(false);
  async function submit(data: FormData) { setPending(true); setMessage(""); const result = await saveLender(data); setPending(false); if (result?.ok) { dirty.current = false; close(); return; } setMessage(result?.error || "Unable to save this lender. Your changes are still here."); }
  function requestClose() { if (!dirty.current || confirm("Discard unsaved lender changes?")) close(); }
  const comparison = lender?.comparison || {};
  return <div className="cw-admin-dialog-inner"><div className="cw-admin-panel-head"><div><p className="cw-admin-eyebrow">{lender ? "Edit lender" : "New lender"}</p><h2 id="lender-editor-title">{lender ? lender.name : "Add lender"}</h2></div><button type="button" className="secondary" onClick={requestClose}>Cancel</button></div>{message && <p className="cw-admin-error" role="alert">{message}</p>}<form ref={form} action={submit} onChange={() => { dirty.current = true; }} className="cw-admin-form"><input name="id" type="hidden" value={lender?._id || ""}/><fieldset><legend>Basic information</legend><label>Name<input name="name" required defaultValue={lender?.name}/></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" defaultValue={lender?.slug}/></label><label>Category<select name="lenderType" defaultValue={lender?.lenderType || "BANK"}><option>BANK</option><option>NBFC</option><option>INTERNATIONAL</option></select></label><label>Display order<input name="displayOrder" type="number" min="0" defaultValue={lender?.displayOrder ?? 0}/></label></fieldset><fieldset><legend>Branding and links</legend><label>Logo URL<input name="logoUrl" type="url" defaultValue={String(lender?.logoUrl || "")}/></label><label>Application URL<input name="applicationUrl" type="url" defaultValue={String(lender?.applicationUrl || "")}/></label></fieldset><fieldset><legend>Loan information</legend>{comparisonFields.map(([name, label, key]) => <label key={name}>{label}<input name={name} defaultValue={comparison[key] || ""} placeholder="Not available"/></label>)}</fieldset><fieldset><legend>Publication settings</legend><label>Visibility<select name="published" defaultValue={lender?.published ? "true" : "false"}><option value="true">Published</option><option value="false">Unpublished</option></select></label></fieldset><div className="cw-admin-dialog-actions"><button type="button" className="secondary" onClick={requestClose}>Cancel</button><button className="cw-admin-primary" disabled={pending}>{pending ? "Saving…" : "Save lender"}</button></div></form></div>;
}
