import { AdminShell } from "@/components/admin-shell";
import { AdminIconSubmitButton } from "@/components/admin-icon-submit-button";
import { AdminUserCreateDialog } from "@/components/admin-user-create-dialog";
import { AdminUserDeleteAction } from "@/components/admin-user-delete-action";
import { AdminUserPasswordReset } from "@/components/admin-user-password-reset";
import { updateAdminUser } from "@/app/admin/actions";
import { requireRole } from "@/lib/admin-auth";
import { connectToDatabase } from "@/lib/mongodb";
import { AdminUser, Role } from "@/lib/models";
export default async function Users({searchParams}:{searchParams:Promise<{notice?:string}>}){const admin=await requireRole("SUPER_ADMIN");const query=await searchParams;await connectToDatabase();const roleDoc=await Role.findOne({key:"STAFF"}).lean() as {_id:unknown}|null;const users=await AdminUser.find(roleDoc?{roleId:roleDoc._id}:{_id:null}).select("name email active mustChangePassword lastLoginAt").lean() as unknown as Array<{_id:unknown;name:string;email:string;active:boolean;mustChangePassword:boolean;lastLoginAt?:Date}>;const role=admin.roleId as unknown as {name?:string}|null;return <AdminShell name={admin.name} role={role?.name||"Super Admin"}><div className="cw-admin-page-heading cw-admin-users-heading"><div><h1>Staff Admin Management</h1><p className="cw-admin-kicker">Create, edit, suspend, reset, or remove Staff Admin accounts. Passwords are never visible.</p></div><AdminUserCreateDialog/></div>{query.notice==="admin-deleted"?<p className="cw-admin-success" role="status">Staff Admin account deleted.</p>:null}<section className="cw-admin-panel cw-admin-users-panel"><div className="cw-admin-panel-head"><div><p className="cw-admin-eyebrow">Team access</p><h2>Staff Admin accounts</h2></div></div><div className="cw-admin-table-wrap"><table className="cw-admin-users-table"><thead><tr><th>Account</th><th>Role</th><th>Status</th><th>Last active</th><th>Actions</th></tr></thead><tbody>{users.length?users.map(user=>{const formId=`staff-${String(user._id)}`;const status=!user.active?"Suspended":user.mustChangePassword?"Temporary password": "Active";return <tr key={String(user._id)}><td data-label="Account"><input name="name" form={formId} defaultValue={user.name} aria-label={`Name for ${user.name}`}/><input name="email" form={formId} defaultValue={user.email} aria-label={`Email for ${user.name}`}/></td><td data-label="Role"><span className="cw-admin-role-badge is-staff">Staff Admin</span></td><td data-label="Status"><select name="active" form={formId} defaultValue={user.active?"true":"false"} aria-label={`Status for ${user.name}`}><option value="true">Active</option><option value="false">Suspended</option></select><small>{status}</small></td><td data-label="Last active">{user.lastLoginAt?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(user.lastLoginAt):"Never"}</td><td data-label="Actions" className="cw-admin-user-actions"><form id={formId} action={updateAdminUser}><input type="hidden" name="id" value={String(user._id)}/><AdminIconSubmitButton className="cw-admin-icon-action is-edit" label={`Save ${user.name}`} tooltip="Save changes" pendingLabel="Saving"><span aria-hidden="true">✓</span></AdminIconSubmitButton></form><AdminUserPasswordReset id={String(user._id)} name={user.name}/><AdminUserDeleteAction id={String(user._id)} name={user.name}/></td></tr>}):<tr><td colSpan={5} className="cw-admin-empty">No Staff Admin accounts yet.</td></tr>}</tbody></table></div></section></AdminShell>}
