import { randomUUID } from "crypto";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { NextResponse } from "next/server";
import { put } from "@vercel/blob";
import { allowRequest } from "@/lib/api";
const types = new Map([["image/jpeg", "jpg"], ["image/png", "png"], ["image/webp", "webp"]]); const max = 3 * 1024 * 1024;
function valid(bytes: Uint8Array, type: string) { return type === "image/jpeg" ? bytes[0] === 255 && bytes[1] === 216 : type === "image/png" ? bytes.slice(0, 8).every((b, i) => b === [137,80,78,71,13,10,26,10][i]) : type === "image/webp" && new TextDecoder().decode(bytes.slice(0,4)) === "RIFF" && new TextDecoder().decode(bytes.slice(8,12)) === "WEBP"; }
export async function POST(request: Request) { if (!allowRequest(request, 4)) return NextResponse.json({ error: "Please try again later." }, { status: 429 }); const file = (await request.formData()).get("image"); if (!(file instanceof File) || !types.has(file.type) || file.size > max) return NextResponse.json({ error: "Choose a JPG, PNG, or WebP photo up to 3 MB." }, { status: 400 }); const bytes = new Uint8Array(await file.arrayBuffer()); if (!valid(bytes, file.type)) return NextResponse.json({ error: "The photo file could not be verified." }, { status: 400 }); const filename = `${randomUUID()}.${types.get(file.type)}`; if (process.env.BLOB_READ_WRITE_TOKEN) { const blob = await put(`testimonial-submissions/${filename}`, Buffer.from(bytes), { access: "public", contentType: file.type, addRandomSuffix: false }); return NextResponse.json({ url: blob.url }, { status: 201 }); } if (process.env.VERCEL) return NextResponse.json({ error: "Photo uploads are not configured." }, { status: 503 }); const folder = path.join(process.cwd(), "public", "uploads", "testimonials"); await mkdir(folder, { recursive: true }); await writeFile(path.join(folder, filename), bytes); return NextResponse.json({ url: `/uploads/testimonials/${filename}` }, { status: 201 }); }
